# Generated by Django 3.2.9 on 2021-11-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('movie', 'Movie'), ('book', 'Book')], max_length=15)),
                ('image', models.URLField(default=None, null=True)),
                ('average_rating', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
