# Generated by Django 3.2.9 on 2021-11-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='image',
            field=models.ImageField(default=None, upload_to='img/'),
        ),
    ]
