# Generated by Django 3.2.9 on 2021-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211205_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='average_star_rating',
            field=models.FloatField(default=0),
        ),
    ]
